name: Mr.Kittisak Taoma
url: "https://kittisaktaoma.github.io"
baseurl: '/yCV' 
permalink: pretty

# Social icons
facebook: smilely.yean
linkedin: kittisak-taoma-2b9973182
github: kittisaktaoma
twiiter: K_taoma
Email: kittisak.tao@student.mahidol.edu
