name: Mr.Kittisak Taoma
url: "https://kittisaktaoma.github.io"
baseurl: '/yCV' 
permalink: pretty

# Social icons
linkedin: kittisak-taoma-2b9973182
github: kittisaktaoma
twiiter: K_taoma
Email: Kittisaktaoma18@gmail.com
