url: "https://kittisaktaoma.github.io"
baseurl: '/yCV' #change it according to your repository name
permalink: pretty

# Social icons
facebook: Jolene Jolene
linkedin: Kittisak Taoma
github: kittisaktaoma
twiiter: K_taoma
