name: Mr.Kittisak Taoma
url: "https://kittisaktaoma.github.io"
baseurl: '/yCV' #change it according to your repository name
permalink: pretty

# Social icons
facebook: smilely.yean
linkedin: kittisak-taoma-2b9973182
github: kittisaktaoma
twiiter: K_taoma
gmail: Kittisaktaoma18@gmail.com
